// const MACHINE_IP = '127.0.0.1';
const MACHINE_IP = '3.91.111.224';
const API_USER_URL = `http://${MACHINE_IP}:8000`;
const API_RATING_URL = `http://${MACHINE_IP}:8001`;
const API_PARK_URL = `http://${MACHINE_IP}:8002`;
const API_BOOKING_URL = `http://${MACHINE_IP}:8003`;
const API_REPORTS_URL = `http://${MACHINE_IP}:8004`;

export const api = {
    USER_URL: API_USER_URL,
    RATING_URL: API_RATING_URL,
    PARK_URL: API_PARK_URL,
    BOOKING_URL: API_BOOKING_URL,
    REPORTS_URL : API_REPORTS_URL
}
